### ISSUE TITLE
No MIPS using git clone?

### ISSUE THREAD

**Issue by 0x80O0oOverfl0w** [MIPS/FreeRTOS#11]
Using standard git clone <repo name>, the MIPS32_GCC folder does not exist in the FreeRTOS/FreeRTOS/Demo folder. Likewise, lwIP_MIPS_GCC does not exist either. Both of these folders exist when downloading the repo as a .zip file.

**Comment by chrisdearman** [comment]
By default git clone will checkout the master branch. Take a look at the mips branch instead. Eg:
https://github.com/MIPS/FreeRTOS/tree/mips/FreeRTOS/Demo/lwIP_MIPS_GCC

**Comment by 0x80O0oOverfl0w** [comment]
Sure enough, git branch -a shows the mips branch and the mips demos are available after checking out the mips branch.
